#!/usr/bin/env bash
#
# This script takes a subdomain and a domain as input and returns information about the subdomain.
# It provides information such as the IP address, SSL certificate detailswhich has not been assigned yet, and other relevant information.
# The script can be used to gather information about a specific subdomain for troubleshooting or analysis purposes.
#
# Usage: ./script.sh <subdomain> <domain>
#
# Example: ./script.sh www example.com
#
# Note: Make sure to replace <subdomain> and <domain> with the actual values you want to query.
# 
print_info () {
    dig "$1" | grep -A1 'ANSWER SECTION:' | sed -r "s/$1./$2/g" | awk -F" " ' NR==2 { print "The subdomain " $1 " is a " $4 " record and points to " $5 }'
}

if [ "$#" -eq 2 ]
then
    print_info "$2.$1" "$2"
else
    print_info "www.$1" "www"
    print_info "lb-01.$1" "lb-01"
    print_info "web-01.$1" "web-01"
    print_info "web-02.$1" "web-02"
fi