#!/usr/bin/env bash
# A script that takes in argument from the command line to
# securely send files to a remote server or shell

if [ $# -lt 3 ];
then
    echo "0-transfer_file PATH_TO_FILE IP USERNAME PATH_TO_SSH_KEY"
    exit;
fi;

if [ $# -ge 4 ];
then
    scp -o "StrictHostKeyChecking=no" -i "$4" "$1" "$3@$2":~/;
fi;