#!/usr/bin/env bash 
# A script that installs nginx server and displays html content

sudo apt-get -y update
sudo apt-get -y install nginx
echo "Hello World!" > /var/www/html/index.nginx-debian.html
sudo service nginx start