#!/usr/bin/env bash 
# A script that installs nginx server and displays html content

sudo apt-get update -y
sudo apt-get install nginx -y
echo "Hello World!" > /var/www/html/index.nginx-debian.html
sudo service nginx start