#!/usr/bin/env bash

# Configure web-02 to mirror the settings of web-01
# Introduce a custom HTTP header with the name X-Served-By
# Populate the custom HTTP header with the hostname of the Nginx server

sudo apt-get -y update
sudo apt-get -y install nginx
sudo ufw allow 'Nginx HTTP'
sudo mkdir -p /var/www/html /var/www/error
sudo chmod -R 755 /var/www
echo 'Hello World!' > /var/www/html/index.html
echo "This is not a valid web page." > /var/www/html/404.html
nginx_configuration=\
"server {
listen 80 default_server;
listen [::]:80 default_server;
root /var/www/html;
index index.html index.htm index.nginx-debian.html;
server_name _;
add_header X-Served-By \$hostname;
location / {
try_files \$uri \$uri/ =404;
}
if (\$request_filename ~ redirect_me){
rewrite ^ https://youtube.com permanent;
}
error_page 404 /404.html;
location = /404.html {
internal;
}
}"

echo "$nginx_configuration" > /etc/nginx/sites-enabled/default
sudo service nginx restart
