#!/usr/bin/env bash

# A command that installs haproxy.

apt-get -y install haproxy

# Modifies the configuration for haproxy
backend_frontend_config=\
"
frontend  azil-frontend-config
        bind *:80
        mode http
        default_backend azil-backend-config
backend azil-backend-config
        balance roundrobin
        server 313912-web-01 3.94.213.246 check
        server 313912-web-02 54.175.54.105 check
"
 echo "$backend_frontend_config" >> /etc/haproxy/haproxy.cfg

 # A command that configures haproxy to start by init script
 # however making it to start right after the servers boots.

 echo "ENABLED=1" >> /etc/default/haproxy

 sudo service haproxy restart
 