#!/usr/bin/env bash

# Update package lists
sudo apt-get update

# A command that installs haproxy
sudo apt-get -y install haproxy

# Modifies the configuration for haproxy
backend_frontend_config=\
"
frontend  azil-frontend-config
        bind *:80
        mode http
        default_backend azil-backend-config
backend azil-backend-config
        balance roundrobin
        server 313912-web-01 54.236.232.200 check
        server 313912-web-02 3.95.32.126 check
"
sudo echo "$backend_frontend_config" >> /etc/haproxy/haproxy.cfg

# Enable the HAProxy service to be managed by the init script
sudo echo "ENABLED=1" >> /etc/default/haproxy

# Enable the HAProxy service to start at boot time (systemd)
sudo systemctl enable haproxy

# Restart the HAProxy service to apply the changes
sudo service haproxy restart