#!/usr/bin/env bash
# A command that starts apache server in docker container

echo "Hello Holberton" > /var/www/html/index.html

echo "ServerName localhost" >> /etc/apache2/apache2.conf
service apache2 start
