#!/usr/bin/env bash
# A command that starts apache server in docker container

echo "ServerName localhost" >> /etc/apache2/apache2.conf
service apache2 start

if service apache2 status | grep -q "apache2 is running"; then
  echo "apache2 is running"
fi
